spring:
  application:
    name: banking-cqrs-es

  datasource:
    url: jdbc:postgresql://localhost:5434/banking_db
    username: postgres
    password: itachi
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    org.axonframework: INFO

axon:
  axonserver:
    enabled: false